### ISSUE TITLE
Gradle plugin always invalidates configuration cache on github actions, when ratchetFrom is set

### ISSUE THREAD

**Issue by superxiao** [diffplug/spotless#2249]
If you are submitting a **bug**, please include the following:

- [x] summary of problem
- [x] Gradle or Maven version
- [x] spotless version
- [x] operating system and version
- [x] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [ ] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

Gradle: 8.10
Spotless gradle plugin: 7.0.0.BETA2
When the spotless gradle plugin is used, configuration cache on github actions using [`setup-gradle`](https://github.com/gradle/actions/blob/main/setup-gradle/README.md) usually fails with the [following message](https://github.com/superxiao/spotless-gradle-bug-demo/actions/runs/10771803627/job/29868089663#step:5:28):
```
Calculating task graph as configuration cache cannot be reused because the file system entry '.git/refs/remotes/origin/.probe-8edb64c1-4909-420b-b493-b18d007910f4' has been removed.
```
Spotless config:
```
spotless {
    ratchetFrom("origin/main")
    java {
        googleJavaFormat()
    }
}
```
Without `ratchetFrom`, it's [this](https://github.com/superxiao/spotless-gradle-bug-demo/actions/runs/10771722651/job/29867835022#step:5:28),
```
Reusing configuration cache.
```
It seems the spotpless plugin introduces git and the entire .git folder as an input for configuration cache of some sort, with `ratchetFrom`.

[This issue](https://github.com/gradle/gradle/issues/23895) may be related.

Here is a [sample repo](https://github.com/superxiao/spotless-gradle-bug-demo) where this can reproduce. You would run the .github/workflows/gradle.xml (can be dispatched manually or on pull request/push) action once to generate cache from the `setup-gradle` action which is invoked inside. A subsequent run should reuse configuration cache, but does not. When you remove `ratchetFrom`, clear github cache, and run the action twice, the configuration cache is reused.

**Comment by superxiao** [comment]
I dealt with this issue by turning off `ratchetFrom` for CI:
```
spotless {
  if (System.getenv("CI") == null) {
    ratchetFrom("origin/develop")
  }
...
}
 ```
 
 And then have a dedicated job to run static analysis (including spotless), with explicitly specified files:
 
 ```
       - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: src/**/*.java
          separator: ","
 
       - name: Run static analysis
        run: |
          ./gradlew compileTestJava checkstyleMain checkstyleTest spotlessCheck \
          -PspotlessFiles=${{ steps.changed-files.outputs.all_changed_files }}
 ```
 
 Note, since the changed files will change every time, this job will not reuse configuration cache. However, all other jobs (e.g. running tests) can skip spotless `-x spotlessApply` and reuse configuration cache.
